# docker pull gcr.io/google-samples/node-hello:1.0
# docker tag gcr.io/google-samples/node-hello:1.0 reg.toxics.space/hello
# docker image push reg.toxics.space/hello
# curl http://reg.toxics.space/v2/_catalog

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "selectorLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
      - name: secret-dockercfg
      containers:
      - image: gcr.io/google-samples/node-hello:{{ .Values.version }}
        imagePullPolicy: Always
        name: hello-world
        ports:
        - name: helloworld-port
          containerPort: 8080
